const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const sessions=[
{type:"BUILD",name:"Build A",desc:"Foundation strength • Push, pull, legs & core",warm:["Wrist circles — 20 sec","Arm swings + shoulder rolls — 30 sec","Easy sit-to-stand — 8 reps","Very easy wall push-up — 6 reps"],work:[
["Wall Push-up","2 × 6–10","reps","Stand facing a wall, hands around chest height. Bend elbows and bring chest toward wall, then press away.","Body straight|Elbows roughly 30–45°|Control both directions"],
["Chair Sit-to-Stand","2 × 8–10","reps","Sit to a stable chair under control, then stand tall without throwing your torso forward.","Knees track with toes|Whole foot planted|Stand tall"],
["Band Row","2 × 8–12","reps","Anchor the band safely around a stable point, pull handles toward your ribs, then return slowly.","Shoulders away from ears|Squeeze shoulder blades|Don't jerk"],
["Elevated Plank","2 × 15–20","sec","Place forearms or hands on a stable elevated surface and hold a straight body line.","Brace abs|Squeeze glutes|Don't sag"]],cool:["Easy chest opening — 30 sec","Slow breathing — 30 sec"]},
{type:"LIGHT",name:"Light A",desc:"Technique • Balance • joint control",warm:["Wrist prep — 30 sec","Shoulder circles — 30 sec","Hip circles — 30 sec"],work:[
["Feet-Assisted Dip Support","3 × 10","sec","Stand between dip bars. Press down with straight arms while feet remain on the floor and assist as much as needed.","Shoulders down|Arms straight but comfortable|Feet control difficulty"],
["Supported Single-Leg Stand","2 × 20","sec","Stand beside a stable support and balance on one leg, using fingertips if needed.","Tall posture|Soft knee|Steady breathing"],
["Seated Tuck Compression","2 × 6–8","reps","Sit with legs in front, hands beside thighs, brace and try to lift one or both heels slightly.","Stay tall|Move from hips/core|No painful forcing"]],cool:["Wrist shakeout — 20 sec","Easy forward fold — 30 sec"]},
{type:"BUILD",name:"Build B",desc:"Foundation strength • Alternate practice",warm:["March in place — 30 sec","Wrist + elbow circles — 30 sec","Shoulder blade squeezes — 30 sec"],work:[
["Incline/Wall Push-up","2 × 6–10","reps","Use the easiest safe incline that lets you keep clean form. Higher surface = easier.","Straight body line|Controlled chest descent|Keep reserve"],
["Supported Squat","2 × 8–12","reps","Hold a stable support lightly, sit hips down between your legs, then stand.","Comfortable depth|Knees follow toes|Don't collapse inward"],
["Band Row","2 × 8–12","reps","Pull a safely anchored band toward the lower ribs and return under control.","Chest proud|No shrugging|Slow return"],
["Dead Bug Regression","2 × 5/side","reps","Lie on your back, brace gently, then move one limb at a time without letting your lower back arch excessively.","Slow movement|Breathe|Stop before control is lost"]],cool:["Child's pose or easy back stretch — 30 sec","Slow breathing — 30 sec"]},
{type:"LIGHT",name:"Light B",desc:"Skill foundations • easy quality work",warm:["Wrist rocks — 30 sec","Scapular movement — 30 sec","Ankle circles — 30 sec"],work:[
["Dip-Bar Assisted Support","3 × 10–15","sec","Use your feet to unload your body while pressing firmly into the bars.","No shoulder shrug|Stable elbows|Easy effort"],
["Frog Stand Lean Prep","3 × 10","sec","Hands on floor, knees remain supported by feet; gently shift weight toward hands without committing to a balance.","Spread fingers|Small lean only|Stop for wrist pain"],
["Calf Raise Supported","2 × 12–15","reps","Hold support and rise onto the balls of your feet, pause, then lower slowly.","Even pressure|No bouncing|Full comfortable range"]],cool:["Forearm stretch — 30 sec","Calf stretch — 30 sec"]},
{type:"REHAB",name:"Full-Body Rehab",desc:"Prehab • mobility • flexibility • recovery",warm:["Easy march + breathing — 45 sec","Gentle whole-body joint circles — 45 sec"],work:[
["Wrist Controlled Rocks","1 × 8","reps","Hands on a stable surface, gently shift weight forward and back through a pain-free range.","Gentle pressure|No sharp pain|Slow"],
["Band Shoulder Rotation","1 × 10","reps","Use a very light band and rotate through a comfortable shoulder range.","Light resistance|Elbow controlled|No forcing"],
["Cat-Cow","1 × 8","reps","On hands and knees, slowly alternate comfortable spinal rounding and extension.","Move segmentally|Breathe|Pain-free range"],
["90/90 Hip Switch","1 × 6","reps","Sit with knees bent and gently rotate both legs side to side within your available range.","Stay controlled|Don't force knees|Use hands if needed"],
["Supported Deep Squat Hold","2 × 20","sec","Hold a stable support and sink only as deep as comfortable.","Heels supported if needed|Relax gradually|No joint pain"],
["Hamstring/Pike Stretch","2 × 20","sec","Hinge forward gently with a long spine until a mild stretch is felt.","No bouncing|Mild stretch only|Breathe"],
["Ankle Knee-to-Wall","1 × 8/side","reps","Drive knee gently forward over toes while keeping heel down.","Heel stays down|Knee follows toes|Comfortable range"]],cool:["Relaxed full-body breathing — 60 sec"]}] ;
const defaultState={profile:{height:"",weight:""},sessionIndex:0,history:[],exercise:{},skills:{push:"training",pull:"training",support:"training",core:"training",squat:"training",lSit:"locked",handstand:"locked",dip:"locked"}};
let state=JSON.parse(localStorage.getItem("localisthenics")||"null")||defaultState;
const save=()=>localStorage.setItem("localisthenics",JSON.stringify(state));
function renderToday(){let s=sessions[state.sessionIndex%5];$("#sessionType").textContent=s.type;$("#sessionName").textContent=s.name;$("#sessionDesc").textContent=s.desc;$("#warmup").innerHTML=s.warm.map(x=>`<div class="simple">✓ ${x}</div>`).join("");$("#cooldown").innerHTML=s.cool.map(x=>`<div class="simple">○ ${x}</div>`).join("");$("#doneCount").textContent=0;
$("#workout").innerHTML=s.work.map((e,i)=>`<div class="exercise" data-i="${i}"><div class="ex-top"><div><div class="ex-name">${e[0]}</div><div class="target">Target: ${e[1]}</div></div><button class="ref">How?</button></div><div class="log"><label>Actual<input class="actual" type="number" min="0" placeholder="${e[2]}"></label><label>RIR<input class="rir" type="number" min="0" max="10" placeholder="2–4"></label><label>Form<select class="form"><option>Clean</option><option>Shaky</option><option>Broke down</option></select></label><label>Pain<select class="pain"><option>No</option><option>Mild</option><option>Sharp</option></select></label></div><div class="feedback"></div></div>`).join("");
$$(".exercise").forEach(el=>{let e=s.work[+el.dataset.i];el.querySelector(".ref").onclick=()=>showRef(e);["input","change"].forEach(ev=>el.addEventListener(ev,()=>feedback(el,e)))})}
function feedback(el,e){let n=+el.querySelector(".actual").value,rir=+el.querySelector(".rir").value,form=el.querySelector(".form").value,pain=el.querySelector(".pain").value,out="";if(pain==="Sharp")out="Pause this movement. Do not progress; use a comfortable substitute and reassess.";else if(n===1)out="Too difficult → regress to an easier variation next time.";else if(n>0&&n<5)out="Likely too difficult → regress or increase assistance.";else if(n>=15&&rir>=3&&form==="Clean")out="Very comfortable → next session should progress difficulty, not just pile on reps.";else if(n>0&&rir<=1)out="Near your limit → keep or slightly regress. We want reserve for frequent practice.";else if(n>0)out="Good working range → keep this variation and build clean capacity.";el.querySelector(".feedback").textContent=out}
function showRef(e){$("#refTitle").textContent=e[0];$("#refDemo").textContent="MOVEMENT REFERENCE • "+e[0];$("#refHow").textContent=e[3];$("#refCues").innerHTML=e[4].split("|").map(x=>`<li>${x}</li>`).join("");$("#refDialog").showModal()}
$("#finish").onclick=()=>{let s=sessions[state.sessionIndex%5],logs=[];$$(".exercise").forEach((el,i)=>logs.push({name:s.work[i][0],actual:el.querySelector(".actual").value,rir:el.querySelector(".rir").value,form:el.querySelector(".form").value,pain:el.querySelector(".pain").value}));state.history.push({date:new Date().toISOString().slice(0,10),type:s.type,name:s.name,logs});state.sessionIndex=(state.sessionIndex+1)%5;save();renderAll();};
function renderSkills(){let defs=[["Push Foundation","push"],["Band Pull Foundation","pull"],["Dip-Bar Support","support"],["Core Foundation","core"],["Squat Foundation","squat"],["L-Sit","lSit"],["Handstand","handstand"],["Full Dip","dip"]];$("#skillTree").innerHTML=defs.map(([n,k])=>`<div class="skill ${state.skills[k]}"><b>${n}</b><div class="muted">${state.skills[k].toUpperCase()}</div></div>`).join("")}
let view=new Date();function renderCalendar(){let y=view.getFullYear(),m=view.getMonth();$("#monthTitle").textContent=view.toLocaleString(undefined,{month:"long",year:"numeric"});let first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),h="";for(let i=0;i<first;i++)h+="<div></div>";for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,rec=state.history.find(x=>x.date===ds),today=ds===new Date().toISOString().slice(0,10);h+=`<div class="day ${rec?"done "+rec.type.toLowerCase():""} ${today?"today":""}">${d}${rec?`<small style="display:block;color:#a99bb8">${rec.type}</small>`:""}</div>`}$("#calendarGrid").innerHTML=h}
function renderHistory(){$("#historyList").innerHTML=state.history.length?state.history.slice().reverse().map(x=>`<div class="skill unlocked"><b>${x.date} • ${x.name}</b><div class="muted">${x.logs.filter(l=>l.actual).length} movements logged</div></div>`).join(""):`<p class="muted">No sessions logged yet. Your first one starts today.</p>`}
function renderAll(){renderToday();renderSkills();renderCalendar();renderHistory()}
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active");if(b.dataset.tab==="calendar")renderCalendar()});
$("#profileBtn").onclick=()=>{$("#height").value=state.profile.height;$("#weight").value=state.profile.weight;$("#profileDialog").showModal()};$("#saveProfile").onclick=()=>{state.profile.height=$("#height").value;state.profile.weight=$("#weight").value;save()};$("#prevMonth").onclick=()=>{view.setMonth(view.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{view.setMonth(view.getMonth()+1);renderCalendar()};renderAll();